Pin bokeh
Because of ImportError: cannot import name 'Box' from 'bokeh.models' (/srv/conda/envs/notebook/lib/python3.9/site-packages/bokeh/models/__init__.py)